name: CI

on: [push, pull_request]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: [14.x, 16.x]
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Versions
        run: |
          echo Node:
          node --version
          echo NPM:
          npm --version
      - name: NPM audit
        continue-on-error: true
        run: npm audit
      - name: NPM install (ci)
        run: npm ci
      - name: Lint
        run: npx eslint .
      - name: Build
        run: npm run build
      - name: Flow
        run: npx flow check
      - name: Flow Type Coverage (HTML report)
        run: npx flow-coverage-report --config .flowcoverage-all
      - name: Archive Flow Type Coverage Report
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: Flow Type Coverage Report
          path: flow-coverage/
      - name: Test
        run: npm test -- --verbose --coverage
      - name: Archive Test Code Coverage Report
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: Test Code Coverage Report
          path: coverage/
      - name: Flow Type Coverage (main coverage threshold)
        run: npx flow-coverage-report --config .flowcoverage-main-threshold
      - name: Flow Type Coverage (test coverage threshold)
        run: npx flow-coverage-report --config .flowcoverage-tests-threshold
      - name: Lint Documentation
        run: npm run markdownlint
